CREATE DATABASE TITANIC;
USE TITANIC;
SELECT * FROM TITANIC;

-- QUESTION 1: SELECT ALL COLUMNS FOR ALL PASSENGERS IN THE TITANIC DATASET.
SELECT * FROM TITANIC;

-- QUESTION 2: DISPLAY THE NUMBER OF PASSENGERS IN EACH CLASS (1ST, 2ND, 3RD).
SELECT PCLASS, COUNT(*) AS NUM_PASSENGERS FROM TITANIC
GROUP BY PCLASS;

-- QUESTION 3: FIND THE NUMBER OF MALE AND FEMALE PASSENGERS.
SELECT SEX, COUNT(*) AS NUM_PASSENGERS FROM TITANIC
GROUP BY SEX;

-- QUESTION 4: DISPLAY THE NAMES OF PASSENGERS WHO SURVIVED.
SELECT NAME FROM TITANIC
WHERE SURVIVED = 'SURVIVED';

-- QUESTION 5: FIND THE AVERAGE AGE OF PASSENGERS.
SELECT AVG(AGE) AS AVERAGE_AGE FROM TITANIC;

-- QUESTION 6: LIST THE NAMES AND AGES OF PASSENGERS WHO WERE YOUNGER THAN 18.
SELECT NAME, AGE FROM TITANIC
WHERE AGE < 18;

-- QUESTION 7: DISPLAY THE NUMBER OF PASSENGERS IN EACH EMBARKATION PORT (C, Q, S).
SELECT EMBARKED, COUNT(*) AS NUM_PASSENGERS FROM TITANIC
GROUP BY EMBARKED;

-- QUESTION 8: FIND THE HIGHEST FARE PAID BY ANY PASSENGER.
SELECT MAX(FARE) AS HIGHEST_FARE FROM TITANIC;

-- QUESTION 9: LIST THE AVERAGE AGE OF PASSENGERS FOR EACH CLASS.
SELECT PCLASS, AVG(AGE) AS AVERAGE_AGE FROM TITANIC
GROUP BY PCLASS;

-- QUESTION 10: DISPLAY THE PASSENGER NAMES AND AGES FOR THOSE WHO SURVIVED AND WERE IN 1ST CLASS.
SELECT NAME, AGE FROM TITANIC
WHERE SURVIVED = 'SURVIVED' AND PCLASS = 1;

-- QUESTION 11: FIND THE NUMBER OF PASSENGERS WHO PAID MORE THAN 50 FOR THEIR TICKET.
SELECT COUNT(*) AS NUM_PASSENGERS FROM TITANIC
WHERE FARE > 50;

-- QUESTION 12: LIST THE NAMES OF PASSENGERS WHO DID NOT SURVIVE AND WERE IN 3RD CLASS.
SELECT NAME FROM TITANIC
WHERE SURVIVED = 'SURVIVED' AND PCLASS = 3;

-- QUESTION 13: FIND THE NUMBER OF PASSENGERS WITH MISSING VALUES IN THE "AGE" COLUMN.
SELECT COUNT(*) AS NUM_PASSENGERS FROM TITANIC
WHERE AGE IS NULL;

-- QUESTION 14: DISPLAY THE PASSENGER NAMES AND AGES FOR THOSE WHO EMBARKED AT PORT 'S' AND SURVIVED.
SELECT NAME, AGE FROM TITANIC
WHERE EMBARKED = 'S' AND SURVIVED = 'SURVIVED';

-- QUESTION 15: CALCULATE THE TOTAL NUMBER OF PASSENGERS ON BOARD.
SELECT COUNT(*) AS TOTAL_PASSENGERS FROM TITANIC;

-- QUESTION 16: LIST THE AVERAGE FARE FOR EACH CLASS.
SELECT PCLASS, AVG(FARE) AS AVERAGE_FARE FROM TITANIC
GROUP BY PCLASS;

-- QUESTION 17: DISPLAY THE PASSENGER NAMES AND AGES FOR THOSE WITH A KNOWN AGE AND A FARE GREATER THAN 100.
SELECT NAME, AGE FROM TITANIC
WHERE AGE IS NOT NULL AND FARE > 100;

-- QUESTION 18: FIND THE PERCENTAGE OF PASSENGERS WHO SURVIVED.
SELECT (COUNT(*) * 100.0 / (SELECT COUNT(*) FROM TITANIC)) AS SURVIVAL_PERCENTAGE FROM TITANIC
WHERE SURVIVED = 'SURVIVED';

-- QUESTION 19: LIST THE NAMES OF PASSENGERS WHO WERE IN 2ND CLASS AND HAD A FARE LESS THAN 20.
SELECT NAME FROM TITANIC
WHERE PCLASS = 2 AND FARE < 20;

-- QUESTION 20: DISPLAY THE PASSENGER NAMES AND AGES FOR THOSE WHO DID NOT SURVIVE AND WERE IN 1ST CLASS.
SELECT NAME, AGE FROM TITANIC
WHERE SURVIVED = 'SURVIVED' AND PCLASS = 1;

-- QUESTION 21: FIND THE NUMBER OF PASSENGERS FOR EACH COMBINATION OF CLASS AND GENDER.
SELECT PCLASS, SEX, COUNT(*) AS NUM_PASSENGERS FROM TITANIC
GROUP BY PCLASS, SEX;

-- QUESTION 22: LIST THE NAMES OF PASSENGERS WHO SURVIVED AND WERE IN 3RD CLASS WITH AN AGE LESS THAN 20.
SELECT NAME FROM TITANIC
WHERE SURVIVED = 'SURVIVED' AND PCLASS = 3 AND AGE < 20;

-- QUESTION 23: DISPLAY THE PASSENGER NAMES FOR THOSE WITH THE NAME STARTING WITH 'MR.'.
-- AS PER THE GIVEN NAMING FORMAT IN THE TABLE
SELECT NAME FROM TITANIC
WHERE SUBSTRING_INDEX(SUBSTRING_INDEX(NAME, ',', -1), '.', 1) = ' MR';
 -- OR
SELECT NAME FROM TITANIC
WHERE NAME LIKE '%MR%';

-- QUESTION 24: FIND THE AVERAGE AGE OF MALE AND FEMALE PASSENGERS.
SELECT SEX, AVG(AGE) AS AVERAGE_AGE FROM TITANIC
GROUP BY SEX;

-- QUESTION 25: LIST THE NAMES OF PASSENGERS WHO PAID THE HIGHEST FARE.
SELECT NAME FROM TITANIC
WHERE FARE = (SELECT MAX(FARE) FROM TITANIC);

-- QUESTION 26: FIND THE NUMBER OF PASSENGERS FOR EACH EMBARKATION PORT AND CLASS.
SELECT EMBARKED, PCLASS, COUNT(*) AS NUM_PASSENGERS FROM TITANIC
GROUP BY EMBARKED, PCLASS;

-- QUESTION 27: DISPLAY THE PASSENGER NAMES AND AGES FOR THOSE WHO SURVIVED AND PAID MORE THAN 200 FOR THEIR TICKET.
SELECT NAME, AGE FROM TITANIC
WHERE SURVIVED = 'SURVIVED' AND FARE > 200;

-- QUESTION 28: FIND THE AVERAGE AGE OF PASSENGERS WHO SURVIVED AND THOSE WHO DID NOT.
SELECT SURVIVED, AVG(AGE) AS AVERAGE_AGE FROM TITANIC
GROUP BY SURVIVED;

-- QUESTION 29: LIST THE NAMES OF PASSENGERS WHO WERE IN 1ST CLASS AND HAD AN AGE GREATER THAN 50.
SELECT NAME FROM TITANIC
WHERE PCLASS = 1 AND AGE > 50;

-- QUESTION 30: DISPLAY THE PASSENGER NAMES FOR THOSE WITH THE NAME ENDING WITH 'SSON'.
SELECT NAME FROM TITANIC
WHERE NAME LIKE '%SSON';
